### ISSUE TITLE
get_unlocked_pids Instance Assignment Race

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-web#18]
An exception similar to this would infrequently occur during a recent competition. It appears there is a small window of time in which it is possible that this loop is inappropriately fired.

```
        if pid not in team["instances"]:
                assign_instance_to_team(pid, tid)
```

An example trace:

```
Traceback (most recent call last):
  File "/vagrant/picoCTF-web/api/annotations.py", line 57, in wrapper
    web_result = f(*args, **kwds)
  File "/vagrant/picoCTF-web/api/annotations.py", line 85, in wrapper
    return f(*args, **kwds)
  File "/vagrant/picoCTF-web/api/annotations.py", line 148, in wrapper
    return f(*args, **kwds)
  File "/vagrant/picoCTF-web/api/routes/problem.py", line 17, in get_visible_problems_hook
    return WebSuccess(data=api.problem.get_visible_problems(api.user.get_user()['tid']))
  File "/vagrant/picoCTF-web/api/problem.py", line 801, in get_visible_problems
    unlocked_pids = get_unlocked_pids(tid, category=category)
  File "/vagrant/picoCTF-web/api/cache.py", line 157, in wrapper
    function_result = f(*args, **kwargs)
  File "/vagrant/picoCTF-web/api/problem.py", line 741, in get_unlocked_pids
    assign_instance_to_team(pid, tid)
  File "/vagrant/picoCTF-web/api/problem.py", line 259, in assign_instance_to_team
    raise InternalException("Team with tid {} already has an instance of pid {}.".format(tid, pid))
api.common.InternalException: Team with tid 42481369c19c4ec182bc8646c29aa2d3 already has an instance of pid d708721fcdb31e1d11856005d0e47461.
```

**Comment by tim-becker** [comment]
This race actually isn't that narrow, since there can be a large time gap between when we [grab the team from the db](https://github.com/picoCTF/picoCTF-web/blob/master/api/problem.py#L728) and when we [check their instance list](https://github.com/picoCTF/picoCTF-web/blob/master/api/problem.py#L736).

I might be best to query the db directly in the loop to prevent this.
